import type { AnalysisItem } from '@/types'

export const mockAnalyses: AnalysisItem[] = [
  {
    id: '1',
    name: 'Service Agreement — Acme Corp',
    date: 'Dec 18, 2024',
    time: '14:32',
    risk: 'High',
    clauses: 12,
    score: 8.4,
    status: 'completed',
  },
  {
    id: '2',
    name: 'Software License — TechStart Ltd',
    date: 'Dec 17, 2024',
    time: '11:15',
    risk: 'Medium',
    clauses: 8,
    score: 5.2,
    status: 'completed',
  },
  {
    id: '3',
    name: 'Consulting Contract — BuildCo',
    date: 'Dec 15, 2024',
    time: '09:45',
    risk: 'Low',
    clauses: 5,
    score: 2.1,
    status: 'completed',
  },
  {
    id: '4',
    name: 'Partnership Agreement — InnovateLab',
    date: 'Dec 14, 2024',
    time: '16:20',
    risk: 'High',
    clauses: 15,
    score: 9.1,
    status: 'completed',
  },
  {
    id: '5',
    name: 'NDA — Quantum Systems',
    date: 'Dec 13, 2024',
    time: '13:05',
    risk: 'Low',
    clauses: 3,
    score: 1.8,
    status: 'completed',
  },
  {
    id: '6',
    name: 'Employment Contract — Sarah Chen',
    date: 'Dec 12, 2024',
    time: '10:30',
    risk: 'Medium',
    clauses: 9,
    score: 4.7,
    status: 'completed',
  },
  {
    id: '7',
    name: 'Vendor Agreement — SupplyChain Inc',
    date: 'Dec 11, 2024',
    time: '15:50',
    risk: 'High',
    clauses: 14,
    score: 7.9,
    status: 'completed',
  },
  {
    id: '8',
    name: 'Lease Agreement — Office Tower B',
    date: 'Dec 10, 2024',
    time: '12:00',
    risk: 'Medium',
    clauses: 11,
    score: 6.3,
    status: 'completed',
  },
  {
    id: '9',
    name: 'SaaS Subscription — CloudHost Pro',
    date: 'Dec 9, 2024',
    time: '14:15',
    risk: 'Low',
    clauses: 6,
    score: 2.9,
    status: 'completed',
  },
]